# Generated by Django 4.0.3 on 2022-04-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_longtoshort_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtoshort',
            name='os',
        ),
    ]
